name: CI - unit

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit tests (matrix)
    runs-on: ubuntu-latest
    env:
      APPRAISAL: rails-8.0
      RUBY_VERSION: 3.3
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Install gems for appraisal
        run: |
          bundle exec appraisal "${APPRAISAL}" bundle install --jobs 1 --retry 2
      - name: Run unit tests only
        run: |
          APPRAISAL="${APPRAISAL}" bin/test unit
